# ========================
# Konfigurasi Situs
# ========================

title: Nurimator
email: rotamirun@gmail.com
description: >-
  Membangun ekosistem digital yang kolaboratif dan inovatif
  untuk masa depan yang lebih baik.
baseurl: "" # kosongkan jika di username.github.io
url: "https://nurimator.github.io"
author: nurimator
twitter_username: nurimator
github_username: nurimator

# ========================
# Konfigurasi Postingan
# ========================

paginate: 5
paginate_path: "/id/post/page:num/"

collections:
  article_id:
    output: true
    permalink: /id/articles/:title/
  article_en:
    output: true
    permalink: /en/articles/:title/
  projets_id:
    output: true
    permalink: /id/media/:title/
  resources_id:
    output: true
    permalink: /id/resources/:title/    
  legals:
    output: true
    permalink: /:title/  

# ========================
# Plugin
# ========================

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# ========================
# Default Layout
# ========================

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# ========================
# Pengecualian Build
# ========================

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
