# _config.yml

# -- Pengaturan Situs --
title: Nurimator
email: rotamirun@gmail.com
description: >- # Deskripsi ini akan muncul di meta tag dan feed RSS
  Membangun ekosistem digital yang kolaboratif dan inovatif 
  untuk masa depan yang lebih baik.
baseurl: "" # biarkan kosong jika situs Anda di username.github.io
url: "https://nurimator.github.io" # ganti 'username' dengan nama pengguna GitHub Anda
author: nurimator
twitter_username: nurimator
github_username:  nurimator
paginate: 5
paginate_path: "/id/posts/page:num/"

collections:
  posts_id:
    output: true
    permalink: /id/posts/:title/
  posts_en:
    output: true
    permalink: /en/post/:title/

# -- Pengaturan Build --
# Plugin yang digunakan oleh GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-archive

pagination:
  enabled: true
  per_page: 6 # Jumlah postingan per halaman
  permalink: '/page:num/' # Format URL untuk halaman berikutnya, misal: /page2/
  title: ':title - Halaman :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

#
# Konfigurasi Autogen (dari jekyll-paginate-v2)
# Ini akan membuat halaman-halaman untuk koleksi Anda
#
autopages:
  enabled: true
  
  collections:
    enabled: true
    layouts: 
      - 'collection_archive.html' # Layout untuk arsip koleksi
    title: 'Arsip :collection'
    permalink: '/:collection/'

  categories:
    enabled: true
    layouts:
      - 'category_archive.html' # Layout untuk arsip kategori
    title: 'Kategori: :cat'
    permalink: '/id/posts/:cat' # Sesuaikan dengan struktur URL Anda

  tags:
    enabled: false # Aktifkan jika Anda menggunakan tag
    layouts:
      - 'tag_archive.html'
    title: 'Tag: :tag'
    permalink: '/tag/:tag'

# -- Front Matter Defaults --
# Menetapkan layout default untuk semua postingan dan halaman
defaults:
  - scope:
      path: "" # semua file
      type: "posts" # hanya untuk postingan
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# -- Pengecualian dari Build --
# File/folder yang tidak akan diproses oleh Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
